### ISSUE TITLE
If i connect a ps4 controller the addon thinks its a xbox controller

### ISSUE THREAD

**Issue by Raptorq1** [rsubtil/controller_icons#111]
![Screenshot_20240920-104858](https://github.com/user-attachments/assets/b65e342c-5850-447d-a6a4-33f4668b9723)
If i connect a ps4 controller the addon thinks its a xbox controller oh and for some odd reason the add-on doesn't allow me to run my game within the editor using split screen mode

**Comment by rsubtil** [comment]
> If i connect a ps4 controller the addon thinks its a xbox controller

Can you add some additional info from your current setup? It seems you're working from an Android tablet, is that correct? Is the controller connected through bluetooth, or with a cable?

> for some odd reason the add-on doesn't allow me to run my game within the editor using split screen mode

Is this the error the screenshot refers to? If yes, it seems you're using a `ControllerIconTexture` within your code; can you show that part of the code to better understand your current context?

It's also possible that your code is running in/from an autoload, which is registered before the `ControllerIcons` autoload. If you're using this feature, try to move `ControllerIcons` to the top, before any of your project-specific code runs.

**Comment by Raptorq1** [comment]
> Can you add some additional info from your current setup? It seems you're working from an Android tablet, is that correct? Is the controller connected through bluetooth, or with a cable?
Yes that is correct and the controller is connected via Bluetooth

> Is this the error the screenshot refers to? If yes, it seems you're using a `ControllerIconTexture` within your code; can you show that part of the code to better understand your current context?
yes
> It's also possible that your code is running in/from an autoload, which is registered before the `ControllerIcons` autoload. If you're using this feature, try to move `ControllerIcons` to the top, before any of your project-specific code runs.
Okay but I can't do that because I'm using a sonic engine name sonic Worlds next and it need the engine files to be on top for the engine to work

**Comment by rsubtil** [comment]
Can you try opening this website (https://hardwaretester.com/gamepad), and check the name of the reported controller ?

**Comment by Raptorq1** [comment]
This is what my ps4 shows up as 


![Screenshot_20240922-160303.png](https://github.com/user-attachments/assets/56424772-198f-479f-9e96-9e1f299f91ff)

and this is what my generic controller shows up as


![Screenshot_20240922-160455.png](https://github.com/user-attachments/assets/9d7ced3d-ae25-42c6-ae51-43e4b0218991)

**Comment by rsubtil** [comment]
Could you try modifying the addon code to print the reported controller name? It's possible it is some variation not currently checked, like "PS4 Controller".

Go to `res://addons/controller_icons/Mapper.gd` script, and print the current controller name under the `_get_joypad_type` function:

```gdscript
extends Node
class_name ControllerMapper
...

func _get_joypad_type(device, fallback):
    ...
    var controller_name = Input.get_joy_name(device)
    print("Controller name: ", controller_name) # Add this line here
    ...
```

**Comment by Raptorq1** [comment]
> Could you try modifying the addon code to print the reported controller name? It's possible it is some variation not currently checked, like "PS4 Controller".
> 
> Go to `res://addons/controller_icons/Mapper.gd` script, and print the current controller name under the `_get_joypad_type` function:
> 
> ```gdscript
> extends Node
> class_name ControllerMapper
> ...
> 
> func _get_joypad_type(device, fallback):
>     ...
>     var controller_name = Input.get_joy_name(device)
>     print("Controller name: ", controller_name) # Add this line here
>     ...
> ```

It says playstation controller

**Comment by rsubtil** [comment]
Thank you, so it seems some correct name is being reported, and not a generic name.

Unfortunately it's a vague name, and cannot be used differentiate between PS3/PS4/PS5 variants. The name being this way, it could be from the specific firmware version, from the specific brand if the controller is not an official Sony one, or from a quirk in the Android system, etc... This is simply the reality of relying on controller names for detecting their icons: for these cases, there isn't much that can be done. I'm considering other sources of information to improve this in the future with #66.

For your case specifically, you can implement a custom mapper if you wish to override this behavior for your project. Check out the [Changing controller mapper](https://github.com/rsubtil/controller_icons/blob/master/DOCS.md#changing-controller-mapper) section on the docs (and [Settings](https://github.com/rsubtil/controller_icons/blob/master/DOCS.md#settings) to apply it) on how to do it.

Since it's not an issue with the addon, I'll close this issue now. If you need more help on this topic though, feel free to continue the discussion.
