### ISSUE TITLE
Select button on PS5 controller is shown as L2 button

### ISSUE THREAD

**Issue by martinboue** [rsubtil/controller_icons#50]
Version : 1.1.4
Godot version : 4.0.2

I'm using the ControllerTextureRect node with a path set to my action name "test".
In the godot input mapping settings, i have bind the Select button on my PS5 controller to the action "test". Name of the input event: "Joypad Button 4 (Back, Sony Select, Xbox Back, Nintendo -)".

When running the game, the icon shown is the L2 button and not the select button.
![image](https://user-images.githubusercontent.com/28391199/233804137-0c2b90a3-136f-45d5-8c1d-860fc0c2336f.png)

I think I have found the source of my problem which is the following method:
https://github.com/rsubtil/controller_icons/blob/f57beb4e2da6891e823effdcb5313341a08f4a3c/addons/controller_icons/ControllerIcons.gd#L413-L452

In my case, the select button have a button_index of 4 and it can matches two times :
- with JOY_BUTTON_BACK, which is the correct one
- and whith JOY_AXIS_TRIGGER_LEFT which is the wrong one

The problem is that the match pattern is using both JoyButton enum and JoyAxis enum. Therefore, the index of the enum is not unique.

**Comment by rsubtil** [comment]
Thank you for your detailed report!

This is because Godot 3 allows you to detect the trigger as both a digital button and analogue axis. When the code was ported to Godot 4 I didn't notice this behavior had changed, and the enum names were ported wrongly.

As far as I know, it's no longer possible to detect these triggers as buttons in Godot 4 (https://github.com/godotengine/godot/issues/72636), so I'll changing this mapping.

**Comment by martinboue** [comment]
Thanks, let me know if you need any help. I could try to open a PR if needed.

**Comment by rsubtil** [comment]
> Thanks, let me know if you need any help. I could try to open a PR if needed.

Yeah, if you want, go ahead an open a PR, I appreciate it! :heart:

**Comment by martinboue** [comment]
Here is the pull request: https://github.com/rsubtil/controller_icons/pull/51
